fix tests

diff --git a/docker/the_tale/bin/tt_worker b/docker/the_tale/bin/tt_worker
--- a/docker/the_tale/bin/tt_worker
+++ b/docker/the_tale/bin/tt_worker
@@ -1,8 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
-trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
+trap 'echo "\"${last_command}\" command failed with exit code $?."' ERR
 
 tt_wait_for_core
 
