gh-2628 Подготовка окружения для production

diff --git a/docker/tt_service/bin/tt_run_service b/docker/tt_service/bin/tt_run_service
--- a/docker/tt_service/bin/tt_run_service
+++ b/docker/tt_service/bin/tt_run_service
@@ -1,6 +1,10 @@
-#!/bin/sh
+#!/bin/bash
 
-wait-for-it core_postgresql:5432 -t $TT_WAIT_TIMEOUT
+set -e
+
+trap 'echo "\"${last_command}\" command failed with exit code $?."' ERR
+
+wait-for-it core-postgresql:5432 -t $TT_WAIT_TIMEOUT
 
 tt_django migrate
 
